[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = true

[programs.localnet]
dutch = "77p3Ka2WQ7a9zDS8CAE9r8ELLN5UtWidTMnd4PAnzmoM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build-with-so = "mkdir -p $PWD/target/deploy && anchor build && ln -s $HOME/.cargo/target/sbf-solana-solana/release/dutch.so $PWD/target/deploy/dutch.so"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
